@testable import ArkhamHorrorShared
import CoreGraphics
import Foundation
import ImageIO

/// Builds small, fully synthetic image byte fixtures for
/// ``AssetImageValidatorTests`` and decoder tests.
///
/// PNG, JPEG, and AVIF "happy path" fixtures (``validPNG``, ``validJPEG``,
/// ``validAVIF``) are real, decodable images generated via ImageIO — never
/// an embedded or fetched binary — so they exercise the exact same full-
/// decode path production code uses at cache-publish and presentation
/// time, not merely a metadata-only shell. For the fixed, small set of
/// width/height/format combinations this suite actually uses, the
/// generated bytes are pinned in ``AssetImageFixturePinnedData`` (see
/// that file for full provenance/regeneration details and why: this
/// suite's full concurrent run showed the system AVIF/HEIF encoder can
/// itself stall for minutes under load, independent of this package's
/// own code). Any other combination falls back to a live, lock-
/// serialized encode via ``AssetImageFixtureBuilder/renderUncached(width:height:utType:)``.
/// The remaining AVIF
/// builders below (``syntheticAVIF``, ``avifMissingMeta``) are deliberately
/// adversarial: hand-assembled minimal or malformed ISO-BMFF box trees used
/// only to exercise the fast top-level `ftyp`-brand pre-filter and the
/// full-decode/dimension-metadata rejection path, never expected to
/// validate successfully.
enum AssetImageFixtureBuilder {
    /// A structurally valid PNG signature plus a well-formed `IHDR` chunk
    /// declaring `width`×`height` — everything ``AssetImageValidator``'s
    /// pure, decode-free `parsePNGDimensions` inspects — but with no
    /// `IDAT`/`IEND` chunks at all, so it is not a genuinely decodable
    /// image. Used to prove the cache-publish decode gate (not just the
    /// pure metadata parse) rejects a header-only PNG.
    static func pngHeaderOnly(width: Int, height: Int) -> Data {
        var data = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
        data.append(contentsOf: withUnsafeBytes(of: UInt32(13).bigEndian, Array.init))
        data.append(contentsOf: Array("IHDR".utf8))
        data.append(contentsOf: withUnsafeBytes(of: UInt32(width).bigEndian, Array.init))
        data.append(contentsOf: withUnsafeBytes(of: UInt32(height).bigEndian, Array.init))
        // Bit depth, color type, compression, filter, interlace: values
        // are unchecked by the pure parser, so any placeholder byte works.
        data.append(contentsOf: [8, 6, 0, 0, 0])
        // CRC: also unchecked by the pure parser.
        data.append(contentsOf: [0, 0, 0, 0])
        return data
    }

    /// A structurally valid JPEG `SOI` plus a minimal start-of-frame
    /// segment declaring `width`×`height` — everything
    /// ``AssetImageValidator``'s pure, decode-free `parseJPEGDimensions`
    /// requires — but with no entropy-coded scan data or `EOI` marker at
    /// all, so it is not a genuinely decodable image. Used to prove the
    /// cache-publish decode gate rejects a header-only JPEG.
    static func jpegHeaderOnly(width: Int, height: Int) -> Data {
        var data = Data([0xFF, 0xD8])
        data.append(contentsOf: [0xFF, 0xC0])
        // Segment length (11: itself + precision + height + width +
        // component count + one 3-byte component descriptor).
        data.append(contentsOf: withUnsafeBytes(of: UInt16(11).bigEndian, Array.init))
        data.append(8) // precision
        data.append(contentsOf: withUnsafeBytes(of: UInt16(height).bigEndian, Array.init))
        data.append(contentsOf: withUnsafeBytes(of: UInt16(width).bigEndian, Array.init))
        data.append(1) // component count
        data.append(contentsOf: [1, 0x11, 0]) // Ci, HiVi, Tqi
        return data
    }

    // MARK: - Real, decodable PNG/JPEG/AVIF

    static func validPNG(width: Int = 4, height: Int = 4) -> Data {
        render(width: width, height: height, utType: "public.png")
    }

    static func validJPEG(width: Int = 4, height: Int = 4) -> Data {
        render(width: width, height: height, utType: "public.jpeg")
    }

    /// A genuinely AV1-coded, ImageIO-decodable AVIF image, generated at
    /// test time the same way ``validPNG``/``validJPEG`` are — this
    /// package encodes it locally via `CGImageDestinationCreateWithData`
    /// with a `"public.avif"` UTType (supported by ImageIO on every
    /// platform this package deploys to; see `Package.swift`'s `.v26`
    /// floor), never embedding or fetching an official image binary.
    static func validAVIF(width: Int = 4, height: Int = 4) -> Data {
        render(width: width, height: height, utType: "public.avif")
    }

    /// Resolves a fixture from ``AssetImageFixturePinnedData`` when this
    /// exact width/height/format combination has been pinned, falling
    /// back to a live, memoized, lock-serialized ``renderUncached`` call
    /// otherwise. See ``AssetImageFixturePinnedData`` for why the
    /// "happy path" fixtures are pinned rather than always live-encoded.
    private static func render(width: Int, height: Int, utType: String) -> Data {
        let cacheKey = RenderCacheKey(width: width, height: height, utType: utType)
        if let pinned = pinnedFixtures[cacheKey] {
            return pinned
        }

        // Only reached for a width/height/format combination that has not
        // been pinned. Serialized and memoized for the same reason the
        // (now-pinned) happy-path fixtures originally needed it: many
        // concurrent callers of the same unpinned combination must not
        // pile up concurrent calls into the shared system codec service.
        return renderCache.withLock { storage in
            if let cached = storage[cacheKey] {
                return cached
            }
            let data = renderUncached(width: width, height: height, utType: utType)
            storage[cacheKey] = data
            return data
        }
    }

    private struct RenderCacheKey: Hashable {
        let width: Int
        let height: Int
        let utType: String
    }

    private static let pinnedFixtures: [RenderCacheKey: Data] = {
        func decode(_ base64: String) -> Data {
            guard let data = Data(base64Encoded: base64) else {
                preconditionFailure(
                    "Pinned fixture base64 in AssetImageFixturePinnedData must decode"
                )
            }
            return data
        }
        return [
            RenderCacheKey(width: 4, height: 4, utType: "public.avif"):
                decode(AssetImageFixturePinnedData.avif4x4),
            RenderCacheKey(width: 8, height: 8, utType: "public.avif"):
                decode(AssetImageFixturePinnedData.avif8x8),
            RenderCacheKey(width: 3, height: 4, utType: "public.avif"):
                decode(AssetImageFixturePinnedData.avif3x4),
            RenderCacheKey(width: 4, height: 4, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png4x4),
            RenderCacheKey(width: 6, height: 4, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png6x4),
            RenderCacheKey(width: 6, height: 6, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png6x6),
            RenderCacheKey(width: 6, height: 9, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png6x9),
            RenderCacheKey(width: 100, height: 100, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png100x100),
            RenderCacheKey(width: 200, height: 200, utType: "public.png"):
                decode(AssetImageFixturePinnedData.png200x200),
            RenderCacheKey(width: 4, height: 4, utType: "public.jpeg"):
                decode(AssetImageFixturePinnedData.jpeg4x4),
            RenderCacheKey(width: 12, height: 5, utType: "public.jpeg"):
                decode(AssetImageFixturePinnedData.jpeg12x5),
            RenderCacheKey(width: 8, height: 8, utType: "public.jpeg"):
                decode(AssetImageFixturePinnedData.jpeg8x8),
        ]
    }()

    /// An `NSLock`-guarded cache box, used only for the live-encode
    /// fallback path above. All access goes through ``withLock(_:)``,
    /// which is the sole synchronization mechanism for the wrapped
    /// dictionary, making the `@unchecked Sendable` below sound.
    private static let renderCache = LockedRenderCache()

    private final class LockedRenderCache: @unchecked Sendable {
        private let lock = NSLock()
        private var storage: [RenderCacheKey: Data] = [:]

        func withLock<T>(_ body: (inout [RenderCacheKey: Data]) -> T) -> T {
            lock.lock()
            defer { lock.unlock() }
            return body(&storage)
        }
    }

    /// The actual ImageIO encoder — the generator this package's pinned
    /// fixtures were captured from. See ``AssetImageFixturePinnedData``
    /// for provenance and regeneration instructions.
    static func renderUncached(width: Int, height: Int, utType: String) -> Data {
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        guard let context = CGContext(
            data: nil,
            width: width,
            height: height,
            bitsPerComponent: 8,
            bytesPerRow: 0,
            space: colorSpace,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else {
            preconditionFailure("Fixture bitmap context creation must succeed for small test sizes")
        }
        context.setFillColor(CGColor(red: 0.8, green: 0.1, blue: 0.1, alpha: 1))
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        guard let cgImage = context.makeImage() else {
            preconditionFailure("Fixture image creation must succeed for a filled bitmap context")
        }
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(data, utType as CFString, 1, nil)
        else {
            preconditionFailure("Fixture image destination creation must succeed for '\(utType)'")
        }
        CGImageDestinationAddImage(destination, cgImage, nil)
        guard CGImageDestinationFinalize(destination) else {
            preconditionFailure("Fixture image finalization must succeed for '\(utType)'")
        }
        return data as Data
    }

    // MARK: - Hand-assembled adversarial AVIF (ISO-BMFF) shells

    /// Builds a byte sequence with a well-formed `ftyp`/`meta`/`iprp`/`ipco`/
    /// `ispe` box structure declaring `width`×`height` (matching what a
    /// real AVIF's primary-item metadata would say) but, deliberately, no
    /// `mdat` (coded picture data) at all. ImageIO correctly detects the
    /// `ftyp` brand from this shell but reports zero decodable items, so
    /// this is rejected as malformed rather than accepted on the strength
    /// of its declared-but-never-backed-by-real-pixels dimensions — see
    /// `AssetImageValidatorTests.avifShellWithNoCodedImageDataRejected`.
    static func syntheticAVIF(width: Int, height: Int, brand: String = "avif") -> Data {
        func box(_ type: String, _ payload: Data) -> Data {
            var result = Data()
            let size = UInt32(8 + payload.count)
            result.append(contentsOf: withUnsafeBytes(of: size.bigEndian, Array.init))
            result.append(contentsOf: Array(type.utf8))
            result.append(payload)
            return result
        }

        var ftypPayload = Data(Array(brand.utf8))
        ftypPayload.append(contentsOf: [0, 0, 0, 0]) // minor version
        ftypPayload.append(contentsOf: Array(brand.utf8)) // one compatible brand: itself
        ftypPayload.append(contentsOf: Array("mif1".utf8))
        let ftyp = box("ftyp", ftypPayload)

        var ispePayload = Data([0, 0, 0, 0]) // version/flags
        ispePayload.append(contentsOf: withUnsafeBytes(of: UInt32(width).bigEndian, Array.init))
        ispePayload.append(contentsOf: withUnsafeBytes(of: UInt32(height).bigEndian, Array.init))
        let ispe = box("ispe", ispePayload)
        let ipco = box("ipco", ispe)
        let iprp = box("iprp", ipco)
        var metaPayload = Data([0, 0, 0, 0]) // meta's own version/flags
        metaPayload.append(iprp)
        let meta = box("meta", metaPayload)

        return ftyp + meta
    }

    /// A truncated AVIF: a well-formed `ftyp` declaring the right brand, but
    /// no `meta` box at all.
    static func avifMissingMeta(brand: String = "avif") -> Data {
        func box(_ type: String, _ payload: Data) -> Data {
            var result = Data()
            let size = UInt32(8 + payload.count)
            result.append(contentsOf: withUnsafeBytes(of: size.bigEndian, Array.init))
            result.append(contentsOf: Array(type.utf8))
            result.append(payload)
            return result
        }
        var ftypPayload = Data(Array(brand.utf8))
        ftypPayload.append(contentsOf: [0, 0, 0, 0])
        ftypPayload.append(contentsOf: Array(brand.utf8))
        return box("ftyp", ftypPayload)
    }

    /// A top-level box (following a well-formed `ftyp`) using the 64-bit
    /// extended-size form (`size32 == 1`) whose declared `size64` is
    /// exactly `Int.max` — the largest value that passes this parser's own
    /// "does size64 fit in an `Int` at all" guard, chosen so that adding it
    /// to this box's own nonzero starting offset (it is not the first box
    /// in the buffer, unlike ``syntheticAVIF``'s `ftyp`) overflows `Int` if
    /// computed with a plain, unchecked `+` rather than
    /// `addingReportingOverflow`. Exercises exactly the top-level box walk
    /// `parseAVIFDimensions` performs directly on the whole buffer,
    /// independent of any AVIF-specific (`meta`/`ispe`) substructure this
    /// validator no longer parses.
    static func avifExtendedSizeOverflowAtNonzeroOffset(brand: String = "avif") -> Data {
        func box(_ type: String, _ payload: Data) -> Data {
            var result = Data()
            let size = UInt32(8 + payload.count)
            result.append(contentsOf: withUnsafeBytes(of: size.bigEndian, Array.init))
            result.append(contentsOf: Array(type.utf8))
            result.append(payload)
            return result
        }

        var ftypPayload = Data(Array(brand.utf8))
        ftypPayload.append(contentsOf: [0, 0, 0, 0])
        ftypPayload.append(contentsOf: Array(brand.utf8))
        ftypPayload.append(contentsOf: Array("mif1".utf8))
        let ftyp = box("ftyp", ftypPayload)

        // A second top-level box (nonzero starting offset) whose header
        // declares the 64-bit extended-size form with the largest
        // `Int`-representable value: `size32 == 1` (4 bytes), a 4-byte
        // type, then an 8-byte `size64` of `Int.max`.
        var overflowingBox = Data(withUnsafeBytes(of: UInt32(1).bigEndian, Array.init))
        overflowingBox.append(contentsOf: Array("meta".utf8))
        overflowingBox.append(
            contentsOf: withUnsafeBytes(of: UInt64(Int.max).bigEndian, Array.init)
        )

        return ftyp + overflowingBox
    }
}
